receitas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('receitasapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

receitasapp/urls.py
from django.urls import path
from receitasapp import views

app_name = 'receitas'

urlpatterns = [
    path('', views.home, name='home'),
    path('receita/search/', views.search, name='search'),
    path('receita/categoria/<int:category_id>/', views.categoria, name='categoria'),
    path('receita/<int:receita_id>/', views.receita, name='receita'),
]

receitasapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Receita(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='receitasapp/cover/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

receitasapp/views.py
from django.http import Http404
from django.shortcuts import render
from utils.receitas.factory import make_recipe
from django.shortcuts import get_list_or_404, get_object_or_404
from django.db.models import Q
from .models import Receita

def home(request):

    receitas = Receita.objects.filter(is_published=True).order_by('-id')

    return render(
        request, 
        'receitas/pages/home.html',
        context={
            'receitas': receitas,
        }
    )

def receita(request, receita_id):

    receita = get_object_or_404(Receita, pk=receita_id, is_published=True)

    return render(
        request, 
        'receitas/pages/receita-view.html',
        context={
            'receita': receita,
            'is_detail_page': True,
            'title': f'{receita.title} - '
        }
    )

def categoria(request, category_id):

    #receitas = Receita.objects.all().filter(category__id = category_pk, is_published=True).order_by('-id')

    receitas = get_list_or_404(
        Receita.objects.all().filter(category__id = category_id, is_published=True).order_by('-id')
    )

    return render(
        request,
        'receitas/pages/category.html',
        context={
            'receitas': receitas,
            'title': f'{receitas[0].category.name} - Category | '
        }
    )

def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404
    
    receitas = Receita.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True
    ).order_by('-id')

    return render(
        request, 
        'receitas/pages/search.html', 
        context={
            'page_title': f'Search for "{search_term}" | ',
            'search_term': search_term,
            'receitas': receitas
        }
    )

receitasapp/templates/receitas/pages/category.html
{% extends "global/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for receita in receitas %}
        {% include "receitas/partials/receita.html" %}
    {% endfor %}
</div>
{% endblock content %}

receitasapp/templates/receitas/pages/home.html
{% extends "global/base.html" %}

{% block title %}Home |{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% if receitas %}
        {% for receita in receitas %}
                {% include "receitas/partials/receita.html" %}
        {% endfor %}
    {% else %}
        <div class="center">
            <h1>Não há receitas no momento.</h1>
        </div>
    {% endif %}
</div>
{% endblock content %}

receitasapp/templates/receitas/pages/receita-view.html
{% extends "global/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include "receitas/partials/receita.html" %}
</div>
{% endblock content %}

receitasapp/templates/receitas/pages/search.html
{% extends "global/base.html" %}

{% block title %}{{page_title}}{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% if receitas %}
        {% for receita in receitas %}
                {% include "receitas/partials/receita.html" %}
        {% endfor %}
    {% else %}
        <div class="center">
            <h1>Não há receitas no momento.</h1>
        </div>
    {% endif %}
</div>
{% endblock content %}

receitasapp/templates/receitas/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Arthur Ribeiro</a>
  </div>

  <div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
  </div>
</footer>

receitasapp/templates/receitas/partials/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/fontawesome.min.css" integrity="sha512-lauN4D/0AgFUGvmMR+knQnbOADyD/XuQ8VF18I8Ll0+TLvsujshyxvU+uzogmQbSq6qJd5jnUdYtK8ShxXMlSg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/brands.min.css" integrity="sha512-7rXIvd/xj1FnI2zKQjjXzDFxC4twqBByp8yxOgEQJs4C/aNzNyoQsOO7VxH0RgYNhbAYLJLwzqslaP50KTTHIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/solid.min.css" integrity="sha512-bdqdas3Yr82pkTg5i0X1gcAT3tBXz/8H3J1ec7RyEKAvr/YiSCJNV2dnkukmL8CicjKb9rxmd+ILK8Kg2o2wvQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'receitas/css/style.css' %}">

receitasapp/templates/receitas/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url "receitas:home" %}">  
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text"> Receitas </span>
            </a>
        </h1>
    </div>
</header>

receitasapp/templates/receitas/partials/receita.html
<div class="receita receita-list-item">
    {% if receita.cover %}
        <div class="receita-cover">
            <a href="{% url "receitas:receita" receita.id %}">
            <img src="{{ receita.cover.url}}" alt="Temporário">
            </a>
        </div>
    {% endif %}
    
    <div class="receita-title-container">
        <h2 class="receita-title">
            <a href="{% url "receitas:receita" receita.id %}">
                {{ receita.title }}
            </a>
        </h2>
    </div>

    <div class="receita-author">
        <span class="receita-author-item">
            <i class="fas fa-user"></i>
            {% if receita.author is not None %}
                {% if receita.author.first_name %}
                    {{ receita.author.first_name }} {{ receita.author.last_name }}
                {% else %}
                    {{ receita.author.username }}
                {% endif %}
            {% else %}
                Autor Deletado
            {% endif %}
        </span>
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ receita.created_at|date:"d/m/Y" }} às {{ receita.created_at|date:"H:i:s" }}
        </span>
        {% if receita.category is not None %}
            <span class="receita-author-item">
                <a href="{% url "receitas:categoria" receita.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ receita.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="receita-content">
        <p>{{ receita.description }}</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                {{ receita.preparation_time }} {{ receita.preparation_time_unit }}
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                {{ receita.servings }} {{ receita.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="receita-footer">
            <a class="receita-read-more button button-dark button-full-width" href="{% url "receitas:receita" receita.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if receita.preparation_steps_html is True %}
                {{ receita.preparation_steps|safe }}
            {% else %}
                {{ receita.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>

receitasapp/templates/receitas/partials/search.html
<div class="search-container">
        <div class="container">
            <form action="{% url "receitas:search" %}" method="GET" class="search-form">
                <input type="search" class="search-input" name="q" value="{{search_term}}" required>
                <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
            </form>
        </div>
</div>